use concurrently to run all services in a single terminal tab

diff --git a/flojoy b/flojoy
--- a/flojoy
+++ b/flojoy
@@ -329,28 +329,28 @@ echo ''
 # Initializing FLOJOY-WATCH RQ Worker
 cd $CWD
 
-npx ttab -t 'Flojoy-watch RQ Worker' "$venvCmd; export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES; rq worker flojoy-watch"
+# npx ttab -t 'Flojoy-watch RQ Worker' "$venvCmd; export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES; rq worker flojoy-watch"
 
-feedback $? 'Starting RQ worker for flojoy-watch in a new tab...' 'Starting RQ worker for flojoy-watch failed, check if ttab is installed (npx ttab) or check if rq worker is installed in your python package'
+# feedback $? 'Starting RQ worker for flojoy-watch in a new tab...' 'Starting RQ worker for flojoy-watch failed, check if ttab is installed (npx ttab) or check if rq worker is installed in your python package'
 
 
-# Initializing FLOJOY RQ Worker
+# # Initializing FLOJOY RQ Worker
 
-npx ttab -t 'RQ WORKER' "$venvCmd; cd PYTHON; export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES; rq worker flojoy"
+# npx ttab -t 'RQ WORKER' "$venvCmd; cd PYTHON; export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES; rq worker flojoy"
 
-feedback $? 'Starting RQ worker for nodes in a new tab...' 'Starting RQ worker for nodes failed, check if ttab is installed (npx ttab) or check if rq worker is installed in your python package'
+# feedback $? 'Starting RQ worker for nodes in a new tab...' 'Starting RQ worker for nodes failed, check if ttab is installed (npx ttab) or check if rq worker is installed in your python package'
 
 # Start the Django server
 
-if lsof -Pi :"$djangoPort" -sTCP:LISTEN -t >/dev/null ; then
-   echo "port $djangoPort is busy, trying with $((djangoPort + 1))"
-   djangoPort=$((djangoPort + 1))
-   npx ttab -t 'Django' "$venvCmd; python3 write_port_to_env.py $djangoPort; python3 manage.py runserver ${djangoPort}"
-else
-   npx ttab -t 'Django' "$venvCmd; python3 write_port_to_env.py $djangoPort; python3 manage.py runserver ${djangoPort}"
-fi
+# if lsof -Pi :"$djangoPort" -sTCP:LISTEN -t >/dev/null ; then
+#    echo "port $djangoPort is busy, trying with $((djangoPort + 1))"
+#    djangoPort=$((djangoPort + 1))
+#    npx ttab -t 'Django' "$venvCmd; python3 write_port_to_env.py $djangoPort; python3 manage.py runserver ${djangoPort}"
+# else
+#    npx ttab -t 'Django' "$venvCmd; python3 write_port_to_env.py $djangoPort; python3 manage.py runserver ${djangoPort}"
+# fi
 
-feedback $? "Starting Django server on port $djangoPort in a new tab..." 'Failed while starting Django server, check error detail printed above!'
+# feedback $? "Starting Django server on port $djangoPort in a new tab..." 'Failed while starting Django server, check error detail printed above!'
 
 
 
@@ -372,5 +372,11 @@ sleep 1
 
 # Initializing React Server
 
-npx ttab -t 'REACT' "$venvCmd; npm start"
-feedback $? 'Starting React server on port 3000 in a new tab...' 'Could not start React server, check is npm installed in your local machine or run the script without -n flag to install the node packages'
+# npx ttab -t 'REACT' "$venvCmd; npm start"
+# feedback $? 'Starting React server on port 3000 in a new tab...' 'Could not start React server, check is npm installed in your local machine or run the script without -n flag to install the node packages'
+
+# start project services
+if [ -n "$venvCmd" ]; then
+   $venvCmd && npm run start-project
+else
+   npm run start-project
